/*
 * Cat Insurance API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EmployeeReq struct {

	FirstName string `json:"firstName"`

	LastName string `json:"lastName"`

	Address *Address `json:"address"`
}
