/*
 * Cat Insurance API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Address struct {

	Street string `json:"street"`

	HouseNumber string `json:"houseNumber"`

	ZipCode float64 `json:"zipCode"`

	City string `json:"city"`
}
