/*
 * Cat Insurance API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CustomerReq struct {

	FirstName string `json:"firstName"`

	LastName string `json:"lastName"`

	Title string `json:"title,omitempty"`

	FamilyStatus string `json:"familyStatus"`

	BirthDate string `json:"birthDate"`

	SocialSecurityNumber string `json:"socialSecurityNumber"`

	TaxId string `json:"taxId"`

	JobStatus string `json:"jobStatus"`

	Address *Address `json:"address"`

	BankDetails *BankDetails `json:"bankDetails"`
}
