/*
 * Cat Insurance API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BankDetails struct {

	Iban string `json:"iban"`

	Bic string `json:"bic"`

	Name string `json:"name"`
}
