/*
 * Cat Insurance API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/v1/",
		Index,
	},

	Route{
		"ContractsContractIdGet",
		strings.ToUpper("Get"),
		"/v1/contracts/{contractId}",
		ContractsContractIdGet,
	},

	Route{
		"ContractsPost",
		strings.ToUpper("Post"),
		"/v1/contracts",
		ContractsPost,
	},

	Route{
		"ContractsRatePost",
		strings.ToUpper("Post"),
		"/v1/contracts/rate",
		ContractsRatePost,
	},

	Route{
		"CustomersCustomerIdContractsGet",
		strings.ToUpper("Get"),
		"/v1/customers/{customerId}/contracts",
		CustomersCustomerIdContractsGet,
	},

	Route{
		"CustomersCustomerIdDelete",
		strings.ToUpper("Delete"),
		"/v1/customers/{customerId}",
		CustomersCustomerIdDelete,
	},

	Route{
		"CustomersCustomerIdPatch",
		strings.ToUpper("Patch"),
		"/v1/customers/{customerId}",
		CustomersCustomerIdPatch,
	},

	Route{
		"CustomersSearchGet",
		strings.ToUpper("Get"),
		"/v1/customers/search",
		CustomersSearchGet,
	},

	Route{
		"CustomersCustomerIdGet",
		strings.ToUpper("Get"),
		"/v1/customers/{customerId}",
		CustomersCustomerIdGet,
	},

	Route{
		"CustomersGet",
		strings.ToUpper("Get"),
		"/v1/customers",
		CustomersGet,
	},

	Route{
		"CustomersPost",
		strings.ToUpper("Post"),
		"/v1/customers",
		CustomersPost,
	},

	Route{
		"EmployeesEmployeeIdGet",
		strings.ToUpper("Get"),
		"/v1/employees/{employeeId}",
		EmployeesEmployeeIdGet,
	},

	Route{
		"EmployeesPatch",
		strings.ToUpper("Patch"),
		"/v1/employees",
		EmployeesPatch,
	},

	Route{
		"EmployeesPost",
		strings.ToUpper("Post"),
		"/v1/employees",
		EmployeesPost,
	},
}
